app = "crvouga-pickflix"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    grace_period = "60s"
    interval = "15s"
    method = "GET"
    path = "/"
    protocol = "http"
    timeout = "10s"
