CREATE DATABASE pickflix;

CREATE TABLE app_user
(
  id BIGSERIAL PRIMARY KEY NOT NULL,
  firebase_id VARCHAR (255) NOT NULL UNIQUE
)

CREATE TABLE todo
(
  id BIGSERIAL PRIMARY KEY NOT NULL,
  task VARCHAR(255) NOT NULL,
  app_user_id BIGINT REFERENCES app_user (id)
)

CREATE TABLE tag
(
  id BIGSERIAL PRIMARY KEY NOT NULL,
  app_user_id BIGINT REFERENCES app_user(id),
  entity_id VARCHAR(255) NOT NULL UNIQUE
)