import { DiscoverActiveTags } from "../discover/redux/discover-active-tags";
import { DiscoverTagsState } from "../discover/redux/discover-tags";
import { PageHistoryState } from "../home/page-history/page-history";
import { AddListItemFormState } from "../lists/forms/add-list-item-form/add-list-item-form";
import { CreateListFormState } from "../lists/forms/create-list-form/create-list-form";
import { DeleteListFormState } from "../lists/forms/delete-list-form/delete-list-form";
import { EditListFormState } from "../lists/forms/edit-list-form/edit-list-form";
import { RemoveListItemsFormState } from "../lists/forms/remove-list-items-form/remove-list-items-form";
import { ToggleListItemFormState } from "../lists/forms/toggle-list-item-form/toggle-list-item-form";
import { moviePageUi } from "../movie/redux/movie-page-ui";
import { PersonPageUiState } from "../person/redux/person-page-ui";
import { DeleteReviewFormState } from "../reviews/form/delete-review/delete-review-form";
import { ReviewFormState } from "../reviews/form/review-form/review-form";
import { SearchState } from "../search/redux/search";
import { SnackbarState } from "../snackbar/redux/snackbar";
import { VideoState } from "../video/redux/video";

export type AppState = {
  toggleListItemForm: ToggleListItemFormState;
  deleteListForm: DeleteListFormState;
  removeListItemsForm: RemoveListItemsFormState;
  deleteReviewForm: DeleteReviewFormState;
  reviewForm: ReviewFormState;
  editListForm: EditListFormState;
  addListItemForm: AddListItemFormState;
  createListForm: CreateListFormState;
  video: VideoState;
  pageHistory: PageHistoryState;
  snackbar: SnackbarState;
  search: SearchState;
  personPageUi: PersonPageUiState;
  moviePageUi: moviePageUi;
  discoverActiveTags: DiscoverActiveTags;
  discoverTags: DiscoverTagsState;
};
